export const ActionTypes = {
    FETCH_CHARCTERS_REQUEST : 'FETCH_CHARCTERS_REQUEST',
    FETCH_CHARCTERS_SUCCESS : 'FETCH_CHARCTERS_SUCCESS',
    FETCH_CHARCTERS_FAILURE : 'FETCH_CHARCTERS_FAILURE',
    EDIT_CHARCTERS_REQUEST : 'EDIT_CHARCTERS_REQUEST',
    EDIT_CHARCTERS_SUCCESS : 'EDIT_CHARCTERS_SUCCESS',
    EDIT_CHARCTERS_FAILURE : 'EDIT_CHARCTERS_FAILURE',
}

export default ActionTypes;