export const ActionTypes = {
    FETCH_CHARCTERS_REQUEST : 'FETCH_CHARCTERS_REQUEST',
    FETCH_CHARCTERS_SUCCESS : 'FETCH_CHARCTERS_SUCCESS',
    FETCH_CHARCTERS_FAILURE : 'FETCH_CHARCTERS_FAILURE',
    FETCH_EPIDOSES_REQUEST : 'FETCH_EPIDOSES_REQUEST',
    FETCH_EPIDOSES_SUCCESS : 'FETCH_EPIDOSES_SUCCESS',
    FETCH_EPIDOSES_FAILURE : 'FETCH_EPIDOSES_FAILURE',
}

export default ActionTypes;